image: node:latest

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script: npm test
