image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script: npm test

deploy:
  stage: deploy
  script:
    - lftp -e "open $FTP_ADDRESS; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete build/ ./; bye"
  only:
    refs:
      - master
