image: xinwangw/node-web-ci:1.0.2

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - node -v
    - rm -rf node_modules/
    - yarn

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - build/
    expire_in: 1 week

test:
  stage: test
  script: npm test

deploy:
  stage: deploy
  script:
    - lftp -e "open $FTP_ADDRESS; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete build/ ./; bye"
  when: manual
  only:
    refs:
      - master
